//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLS
    {
        public BILLS()
        {
            this.Pedidos = new HashSet<Pedidos>();
            this.SALES = new HashSet<SALES>();
        }
    
        public int num_factura { get; set; }
        public string CustumerID { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual ICollection<SALES> SALES { get; set; }
    }
}
