//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.Security = new HashSet<Security>();
        }
    
        public string IDROL { get; set; }
        public string ROL_DESCRIPTION { get; set; }
    
        public virtual ICollection<Security> Security { get; set; }
    }
}
