//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        public int cod_venta { get; set; }
        public int num_factura { get; set; }
        public decimal Sub_total { get; set; }
        public decimal Impuesto_ventas { get; set; }
        public decimal Total_pagar { get; set; }
    
        public virtual BILLS BILLS { get; set; }
    }
}
