//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int IDUsuario { get; set; }
        public string clave { get; set; }
        public string Nombre_Usuario { get; set; }
        public string TIPO_USUARIO { get; set; }
        public bool Clave_temporal { get; set; }
        public string Token { get; set; }
        public int Identificacion { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
